# OWASP ZAP 自动化扫描配置文件
# AIOps Service 认证模块安全测试
#
# 使用方法：
# docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap.sh \
#   -cmd -autorun /zap/wrk/aiops-auth-scan.yaml
#
# 文档：https://www.zaproxy.org/docs/automate/automation-framework/

env:
  contexts:
    - name: "AIOps Auth Context"
      urls:
        - "http://localhost:8080"
      includePaths:
        - "http://localhost:8080/api/v1/auth/.*"
        - "http://localhost:8080/api/v1/session/.*"
        - "http://localhost:8080/api/v1/admin/.*"
      excludePaths:
        - "http://localhost:8080/actuator/.*"
        - "http://localhost:8080/swagger-ui/.*"
        - "http://localhost:8080/v3/api-docs.*"
      authentication:
        method: "json"
        parameters:
          loginPageUrl: "http://localhost:8080/api/v1/auth/login"
          loginRequestUrl: "http://localhost:8080/api/v1/auth/login"
          loginRequestBody: '{"identifier":"{%username%}","password":"{%password%}","rememberMe":false}'
          usernameParameter: "identifier"
          passwordParameter: "password"
        verification:
          method: "response"
          loggedInRegex: "\\Qtoken\\E"
          loggedOutRegex: "\\Q用户名或密码错误\\E"
      sessionManagement:
        method: "headers"
        parameters:
          header: "Authorization"
          headerValue: "Bearer {%token%}"
      users:
        - name: "testuser"
          credentials:
            username: "securitytest"
            password: "SecureP@ss123"

  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
  # 1. 被动扫描 - Spider 爬取
  - type: spider
    parameters:
      context: "AIOps Auth Context"
      maxDuration: 5
      maxDepth: 5
      maxChildren: 10

  # 2. OpenAPI 导入
  - type: openapi
    parameters:
      apiUrl: "http://localhost:8080/v3/api-docs"
      context: "AIOps Auth Context"
      targetUrl: "http://localhost:8080"

  # 3. 被动扫描
  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 10
      scanOnlyInScope: true
      maxBodySizeInBytesToScan: 10000

  - type: passiveScan-wait
    parameters:
      maxDuration: 5

  # 4. 主动扫描 - SQL 注入测试
  - type: activeScan
    parameters:
      context: "AIOps Auth Context"
      policy: "API-Scan"
      maxRuleDurationInMins: 5
      maxScanDurationInMins: 30
    policyDefinition:
      defaultStrength: "medium"
      defaultThreshold: "medium"
      rules:
        # SQL 注入
        - id: 40018  # SQL Injection
          strength: "high"
          threshold: "low"
        - id: 40019  # SQL Injection - MySQL
          strength: "high"
          threshold: "low"
        - id: 40024  # SQL Injection - SQLite
          strength: "medium"
          threshold: "medium"
        # XSS
        - id: 40012  # Reflected XSS
          strength: "high"
          threshold: "low"
        - id: 40014  # Persistent XSS
          strength: "high"
          threshold: "low"
        - id: 40016  # Persistent XSS - Prime
          strength: "medium"
          threshold: "medium"
        - id: 40017  # Persistent XSS - Spider
          strength: "medium"
          threshold: "medium"
        # 认证相关
        - id: 10023  # Information Disclosure - Debug
          strength: "medium"
          threshold: "low"
        - id: 10024  # Information Disclosure - DB
          strength: "high"
          threshold: "low"
        # 会话管理
        - id: 10112  # Session Management Response
          strength: "high"
          threshold: "low"
        # CSRF
        - id: 40014  # CSRF Token Check
          strength: "high"
          threshold: "low"

  # 5. 自定义脚本 - 暴力破解测试
  - type: script
    parameters:
      action: "add"
      type: "standalone"
      engine: "ECMAScript"
      name: "brute-force-test"
      file: "/zap/wrk/scripts/brute-force-test.js"

  - type: script
    parameters:
      action: "run"
      type: "standalone"
      name: "brute-force-test"

  # 6. 自定义脚本 - Token 安全测试
  - type: script
    parameters:
      action: "add"
      type: "standalone"
      engine: "ECMAScript"
      name: "token-security-test"
      file: "/zap/wrk/scripts/token-security-test.js"

  - type: script
    parameters:
      action: "run"
      type: "standalone"
      name: "token-security-test"

  # 7. 生成报告
  - type: report
    parameters:
      template: "traditional-html"
      reportDir: "/zap/wrk/reports"
      reportFile: "aiops-security-report"
      reportTitle: "AIOps Service 安全测试报告"
      reportDescription: "认证模块安全扫描结果"
      displayReport: false

  - type: report
    parameters:
      template: "traditional-json"
      reportDir: "/zap/wrk/reports"
      reportFile: "aiops-security-report"

  # 8. 输出统计
  - type: outputSummary
    parameters:
      format: "long"
      summaryFile: "/zap/wrk/reports/summary.txt"
