openapi: 3.0.3
info:
  title: Report Management API
  description: 报告管理 API（POST-Only）
  version: 1.0.0

servers:
  - url: http://localhost:8081/api/service/v1
    description: Local development

paths:
  /reports/list:
    post:
      summary: 分页查询报告列表
      description: 分页查询报告列表，支持按类型、状态筛选和关键词搜索
      operationId: listReports
      tags:
        - Reports
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListReportsRequest'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResultReportDTO'
        '400':
          description: 参数无效
        '401':
          description: 未认证

  /reports/get:
    post:
      summary: 获取报告详情
      description: 根据ID获取报告详细信息
      operationId: getReport
      tags:
        - Reports
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetReportRequest'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultReportDTO'
        '404':
          description: 报告不存在

  /reports/create:
    post:
      summary: 创建报告
      description: 创建新的报告
      operationId: createReport
      tags:
        - Reports
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReportRequest'
      responses:
        '201':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultReportDTO'
        '400':
          description: 参数无效
        '404':
          description: 关联的拓扑不存在

  /reports/delete:
    post:
      summary: 删除报告
      description: 删除指定的报告
      operationId: deleteReport
      tags:
        - Reports
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteReportRequest'
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
        '404':
          description: 报告不存在

components:
  schemas:
    ListReportsRequest:
      type: object
      properties:
        page:
          type: integer
          minimum: 1
          default: 1
          description: 页码（从1开始）
        size:
          type: integer
          minimum: 1
          maximum: 100
          default: 20
          description: 每页大小
        type:
          type: string
          enum: [Diagnosis, Audit, Performance, Security]
          description: 报告类型筛选
        status:
          type: string
          enum: [Draft, Final, Archived]
          description: 报告状态筛选
        keyword:
          type: string
          description: 关键词搜索（搜索title, summary, tags）
        sortBy:
          type: string
          enum: [created_at, title, type, status]
          default: created_at
          description: 排序字段
        sortOrder:
          type: string
          enum: [asc, desc]
          default: desc
          description: 排序方向

    GetReportRequest:
      type: object
      required:
        - reportId
      properties:
        reportId:
          type: integer
          format: int64
          description: 报告ID

    CreateReportRequest:
      type: object
      required:
        - title
        - type
        - status
        - author
      properties:
        title:
          type: string
          maxLength: 200
          description: 报告标题
        type:
          type: string
          enum: [Diagnosis, Audit, Performance, Security]
          description: 报告类型
        status:
          type: string
          enum: [Draft, Final, Archived]
          description: 报告状态
        author:
          type: string
          maxLength: 100
          description: 作者
        summary:
          type: string
          maxLength: 500
          description: 报告摘要
        content:
          type: string
          description: 报告内容（Markdown格式）
        tags:
          type: array
          items:
            type: string
          description: 标签数组
        topologyId:
          type: integer
          format: int64
          description: 关联的拓扑图ID

    DeleteReportRequest:
      type: object
      required:
        - reportId
      properties:
        reportId:
          type: integer
          format: int64
          description: 报告ID

    ReportDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 报告ID
        title:
          type: string
          description: 报告标题
        type:
          type: string
          enum: [Diagnosis, Audit, Performance, Security]
          description: 报告类型
        status:
          type: string
          enum: [Draft, Final, Archived]
          description: 报告状态
        author:
          type: string
          description: 作者
        summary:
          type: string
          description: 报告摘要
        content:
          type: string
          description: 报告内容
        tags:
          type: array
          items:
            type: string
          description: 标签数组
        topologyId:
          type: integer
          format: int64
          description: 关联的拓扑图ID
        createdAt:
          type: string
          format: date-time
          description: 创建时间

    PageResultReportDTO:
      type: object
      properties:
        code:
          type: integer
          example: 0
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Success
        data:
          type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/ReportDTO'
            page:
              type: integer
            size:
              type: integer
            totalElements:
              type: integer
              format: int64
            totalPages:
              type: integer
            first:
              type: boolean
            last:
              type: boolean

    ResultReportDTO:
      type: object
      properties:
        code:
          type: integer
          example: 0
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          $ref: '#/components/schemas/ReportDTO'

    ResultVoid:
      type: object
      properties:
        code:
          type: integer
          example: 0
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          type: object
          nullable: true
