openapi: 3.0.3
info:
  title: Report Template Management API
  description: 报告模板管理 API（POST-Only）
  version: 1.0.0

servers:
  - url: http://localhost:8081/api/service/v1
    description: Local development

paths:
  /report-templates/list:
    post:
      summary: 分页查询模板列表
      description: 分页查询报告模板列表，支持按分类筛选和关键词搜索
      operationId: listReportTemplates
      tags:
        - Report Templates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListReportTemplatesRequest'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResultReportTemplateDTO'
        '400':
          description: 参数无效

  /report-templates/get:
    post:
      summary: 获取模板详情
      description: 根据ID获取模板详细信息
      operationId: getReportTemplate
      tags:
        - Report Templates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetReportTemplateRequest'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultReportTemplateDTO'
        '404':
          description: 模板不存在

  /report-templates/create:
    post:
      summary: 创建模板
      description: 创建新的报告模板
      operationId: createReportTemplate
      tags:
        - Report Templates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReportTemplateRequest'
      responses:
        '201':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultReportTemplateDTO'
        '400':
          description: 参数无效

  /report-templates/update:
    post:
      summary: 更新模板
      description: 更新报告模板，使用乐观锁防止并发冲突
      operationId: updateReportTemplate
      tags:
        - Report Templates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateReportTemplateRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultReportTemplateDTO'
        '404':
          description: 模板不存在
        '409':
          description: 版本冲突

  /report-templates/delete:
    post:
      summary: 删除模板
      description: 删除指定的报告模板
      operationId: deleteReportTemplate
      tags:
        - Report Templates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteReportTemplateRequest'
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
        '404':
          description: 模板不存在

components:
  schemas:
    ListReportTemplatesRequest:
      type: object
      properties:
        page:
          type: integer
          minimum: 1
          default: 1
          description: 页码（从1开始）
        size:
          type: integer
          minimum: 1
          maximum: 100
          default: 20
          description: 每页大小
        category:
          type: string
          enum: [Incident, Performance, Security, Audit]
          description: 模板分类筛选
        keyword:
          type: string
          description: 关键词搜索（搜索name, description, tags）

    GetReportTemplateRequest:
      type: object
      required:
        - templateId
      properties:
        templateId:
          type: integer
          format: int64
          description: 模板ID

    CreateReportTemplateRequest:
      type: object
      required:
        - name
        - category
        - content
      properties:
        name:
          type: string
          maxLength: 100
          description: 模板名称
        description:
          type: string
          maxLength: 500
          description: 模板描述
        category:
          type: string
          enum: [Incident, Performance, Security, Audit]
          description: 模板分类
        content:
          type: string
          description: 模板内容（含占位符的Markdown）
        tags:
          type: array
          items:
            type: string
          description: 标签数组

    UpdateReportTemplateRequest:
      type: object
      required:
        - templateId
        - version
      properties:
        templateId:
          type: integer
          format: int64
          description: 模板ID
        name:
          type: string
          maxLength: 100
          description: 模板名称
        description:
          type: string
          maxLength: 500
          description: 模板描述
        category:
          type: string
          enum: [Incident, Performance, Security, Audit]
          description: 模板分类
        content:
          type: string
          description: 模板内容
        tags:
          type: array
          items:
            type: string
          description: 标签数组
        version:
          type: integer
          description: 乐观锁版本号

    DeleteReportTemplateRequest:
      type: object
      required:
        - templateId
      properties:
        templateId:
          type: integer
          format: int64
          description: 模板ID

    ReportTemplateDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 模板ID
        name:
          type: string
          description: 模板名称
        description:
          type: string
          description: 模板描述
        category:
          type: string
          enum: [Incident, Performance, Security, Audit]
          description: 模板分类
        content:
          type: string
          description: 模板内容
        tags:
          type: array
          items:
            type: string
          description: 标签数组
        version:
          type: integer
          description: 版本号
        createdAt:
          type: string
          format: date-time
          description: 创建时间
        updatedAt:
          type: string
          format: date-time
          description: 更新时间

    PageResultReportTemplateDTO:
      type: object
      properties:
        code:
          type: integer
          example: 0
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Success
        data:
          type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/ReportTemplateDTO'
            page:
              type: integer
            size:
              type: integer
            totalElements:
              type: integer
              format: int64
            totalPages:
              type: integer
            first:
              type: boolean
            last:
              type: boolean

    ResultReportTemplateDTO:
      type: object
      properties:
        code:
          type: integer
          example: 0
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          $ref: '#/components/schemas/ReportTemplateDTO'

    ResultVoid:
      type: object
      properties:
        code:
          type: integer
          example: 0
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          type: object
          nullable: true
