openapi: 3.0.3
info:
  title: Agent Bound API
  description: |
    Agent 绑定关系管理 API

    提供统一的 Agent 与实体（Topology、Node）绑定管理能力。

    **业务规则**：
    - 每个 Topology 只能绑定一个 GLOBAL_SUPERVISOR
    - 每个 Node 只能绑定一个 TEAM_SUPERVISOR
    - 每个 Node 可以绑定多个 TEAM_WORKER
    - 绑定重复的 Supervisor 时，自动替换现有绑定
  version: 1.0.0
  contact:
    name: AI Ops Team

servers:
  - url: /api/service/v1
    description: 业务接口基路径

tags:
  - name: Agent 绑定管理
    description: Agent-Entity 绑定关系 CRUD 操作

paths:
  /agent-bounds/bind:
    post:
      tags:
        - Agent 绑定管理
      summary: 创建 Agent 绑定
      description: |
        将 Agent 绑定到指定实体。

        **约束**：
        - Agent 的 hierarchyLevel 必须与请求中的 hierarchyLevel 匹配
        - GLOBAL_SUPERVISOR 只能绑定到 TOPOLOGY
        - TEAM_SUPERVISOR/TEAM_WORKER 只能绑定到 NODE
        - 重复绑定 Supervisor 时自动替换
      operationId: bindAgent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BindAgentRequest'
      responses:
        '200':
          description: 绑定成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentBoundResult'
        '400':
          description: 参数错误或绑定约束违反
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
        '404':
          description: Agent 或实体不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'

  /agent-bounds/unbind:
    post:
      tags:
        - Agent 绑定管理
      summary: 解除 Agent 绑定
      description: |
        解除 Agent 与实体的绑定关系（软删除）。
      operationId: unbindAgent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnbindAgentRequest'
      responses:
        '200':
          description: 解绑成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
        '404':
          description: 绑定关系不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'

  /agent-bounds/query-by-entity:
    post:
      tags:
        - Agent 绑定管理
      summary: 按实体查询绑定
      description: |
        查询指定实体的所有 Agent 绑定。
      operationId: queryByEntity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryByEntityRequest'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentBoundListResult'

  /agent-bounds/query-by-agent:
    post:
      tags:
        - Agent 绑定管理
      summary: 按 Agent 查询绑定
      description: |
        查询指定 Agent 的所有绑定关系。
      operationId: queryByAgent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryByAgentRequest'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentBoundListResult'

  /agent-bounds/query-hierarchy:
    post:
      tags:
        - Agent 绑定管理
      summary: 查询层级团队结构
      description: |
        查询指定 Topology 的完整层级团队结构。

        返回结构包含：
        - Global Supervisor（如有）
        - 所有 Node 的 Team Supervisor 和 Workers
      operationId: queryHierarchy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryHierarchyRequest'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HierarchyResult'
        '404':
          description: Topology 不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'

components:
  schemas:
    # Request DTOs
    BindAgentRequest:
      type: object
      required:
        - agentId
        - hierarchyLevel
        - entityId
        - entityType
      properties:
        agentId:
          type: integer
          format: int64
          description: Agent ID
          example: 1
        hierarchyLevel:
          type: string
          enum: [GLOBAL_SUPERVISOR, TEAM_SUPERVISOR, TEAM_WORKER]
          description: 绑定层级
          example: TEAM_SUPERVISOR
        entityId:
          type: integer
          format: int64
          description: 实体 ID（Topology ID 或 Node ID）
          example: 100
        entityType:
          type: string
          enum: [TOPOLOGY, NODE]
          description: 实体类型
          example: NODE
        tenantId:
          type: integer
          format: int64
          description: 租户 ID（网关注入）
        traceId:
          type: string
          description: 追踪 ID（网关注入）
        userId:
          type: integer
          format: int64
          description: 用户 ID（网关注入）

    UnbindAgentRequest:
      type: object
      required:
        - agentId
        - entityId
        - entityType
      properties:
        agentId:
          type: integer
          format: int64
          description: Agent ID
          example: 1
        entityId:
          type: integer
          format: int64
          description: 实体 ID
          example: 100
        entityType:
          type: string
          enum: [TOPOLOGY, NODE]
          description: 实体类型
          example: NODE
        tenantId:
          type: integer
          format: int64
          description: 租户 ID（网关注入）
        traceId:
          type: string
          description: 追踪 ID（网关注入）
        userId:
          type: integer
          format: int64
          description: 用户 ID（网关注入）

    QueryByEntityRequest:
      type: object
      required:
        - entityId
        - entityType
      properties:
        entityId:
          type: integer
          format: int64
          description: 实体 ID
          example: 100
        entityType:
          type: string
          enum: [TOPOLOGY, NODE]
          description: 实体类型
          example: NODE
        hierarchyLevel:
          type: string
          enum: [GLOBAL_SUPERVISOR, TEAM_SUPERVISOR, TEAM_WORKER]
          description: 按层级过滤（可选）
        tenantId:
          type: integer
          format: int64
          description: 租户 ID（网关注入）
        traceId:
          type: string
          description: 追踪 ID（网关注入）
        userId:
          type: integer
          format: int64
          description: 用户 ID（网关注入）

    QueryByAgentRequest:
      type: object
      required:
        - agentId
      properties:
        agentId:
          type: integer
          format: int64
          description: Agent ID
          example: 1
        entityType:
          type: string
          enum: [TOPOLOGY, NODE]
          description: 按实体类型过滤（可选）
        tenantId:
          type: integer
          format: int64
          description: 租户 ID（网关注入）
        traceId:
          type: string
          description: 追踪 ID（网关注入）
        userId:
          type: integer
          format: int64
          description: 用户 ID（网关注入）

    QueryHierarchyRequest:
      type: object
      required:
        - topologyId
      properties:
        topologyId:
          type: integer
          format: int64
          description: Topology ID
          example: 1
        tenantId:
          type: integer
          format: int64
          description: 租户 ID（网关注入）
        traceId:
          type: string
          description: 追踪 ID（网关注入）
        userId:
          type: integer
          format: int64
          description: 用户 ID（网关注入）

    # Response DTOs
    AgentBoundDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 绑定记录 ID
        agentId:
          type: integer
          format: int64
          description: Agent ID
        agentName:
          type: string
          description: Agent 名称
        agentRole:
          type: string
          description: Agent 角色
        hierarchyLevel:
          type: string
          enum: [GLOBAL_SUPERVISOR, TEAM_SUPERVISOR, TEAM_WORKER]
          description: 绑定层级
        entityId:
          type: integer
          format: int64
          description: 实体 ID
        entityType:
          type: string
          enum: [TOPOLOGY, NODE]
          description: 实体类型
        entityName:
          type: string
          description: 实体名称（Topology 或 Node 名称）
        createdAt:
          type: string
          format: date-time
          description: 创建时间

    HierarchyTeamDTO:
      type: object
      properties:
        nodeId:
          type: integer
          format: int64
          description: Node ID
        nodeName:
          type: string
          description: Node 名称
        teamSupervisor:
          $ref: '#/components/schemas/AgentBoundDTO'
        workers:
          type: array
          items:
            $ref: '#/components/schemas/AgentBoundDTO'

    HierarchyStructureDTO:
      type: object
      properties:
        topologyId:
          type: integer
          format: int64
          description: Topology ID
        topologyName:
          type: string
          description: Topology 名称
        globalSupervisor:
          $ref: '#/components/schemas/AgentBoundDTO'
        teams:
          type: array
          items:
            $ref: '#/components/schemas/HierarchyTeamDTO'

    # Standard Response Wrappers
    Result:
      type: object
      properties:
        code:
          type: integer
          description: 状态码
          example: 0
        message:
          type: string
          description: 消息
          example: success
        success:
          type: boolean
          description: 是否成功
          example: true

    ErrorResult:
      type: object
      properties:
        code:
          type: integer
          description: 错误码
        message:
          type: string
          description: 错误消息
        success:
          type: boolean
          example: false

    AgentBoundResult:
      allOf:
        - $ref: '#/components/schemas/Result'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/AgentBoundDTO'

    AgentBoundListResult:
      allOf:
        - $ref: '#/components/schemas/Result'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/AgentBoundDTO'

    HierarchyResult:
      allOf:
        - $ref: '#/components/schemas/Result'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/HierarchyStructureDTO'
