# LLM Service API Contracts - POST-Only
# Feature: 024-post-only-api
# Generated: 2025-12-22

openapi: 3.0.3
info:
  title: LLM Service API (POST-Only)
  version: 2.0.0
  description: LLM service management API with POST-only endpoints

paths:
  /api/v1/llm-services/query:
    post:
      summary: Query LLM services
      operationId: queryLlmServices
      tags: [LLM Services]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryLlmServicesRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedLlmServiceResult'

  /api/v1/llm-services/get:
    post:
      summary: Get LLM service by ID
      operationId: getLlmService
      tags: [LLM Services]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetLlmServiceRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmServiceResult'

  /api/v1/llm-services/create:
    post:
      summary: Create LLM service
      operationId: createLlmService
      tags: [LLM Services]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLlmServiceRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmServiceResult'

  /api/v1/llm-services/update:
    post:
      summary: Update LLM service
      operationId: updateLlmService
      tags: [LLM Services]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLlmServiceRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmServiceResult'

  /api/v1/llm-services/delete:
    post:
      summary: Delete LLM service
      operationId: deleteLlmService
      tags: [LLM Services]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteLlmServiceRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoidResult'

  /api/v1/llm-services/update-status:
    post:
      summary: Update LLM service status
      operationId: updateLlmServiceStatus
      tags: [LLM Services]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLlmServiceStatusRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmServiceResult'

  /api/v1/llm-services/set-default:
    post:
      summary: Set default LLM service
      operationId: setDefaultLlmService
      tags: [LLM Services]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetDefaultLlmServiceRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmServiceResult'

components:
  schemas:
    GatewayInjectableRequest:
      type: object
      properties:
        tenantId:
          type: integer
          format: int64
        traceId:
          type: string
        userId:
          type: string

    QueryLlmServicesRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          properties:
            page:
              type: integer
              minimum: 1
              default: 1
            size:
              type: integer
              minimum: 1
              maximum: 100
              default: 20
            provider:
              type: string
            status:
              type: string
              enum: [ENABLED, DISABLED]

    GetLlmServiceRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [id]
          properties:
            id:
              type: integer
              format: int64

    CreateLlmServiceRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [name, provider, apiKey]
          properties:
            name:
              type: string
            provider:
              type: string
            apiKey:
              type: string
            baseUrl:
              type: string
            model:
              type: string
            config:
              type: object
              additionalProperties: true

    UpdateLlmServiceRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [id]
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            apiKey:
              type: string
            baseUrl:
              type: string
            model:
              type: string
            config:
              type: object
              additionalProperties: true

    DeleteLlmServiceRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [id]
          properties:
            id:
              type: integer
              format: int64

    UpdateLlmServiceStatusRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [id, status]
          properties:
            id:
              type: integer
              format: int64
            status:
              type: string
              enum: [ENABLED, DISABLED]

    SetDefaultLlmServiceRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [id]
          properties:
            id:
              type: integer
              format: int64

    # Response schemas
    Result:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object

    LlmServiceResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    PagedLlmServiceResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    VoidResult:
      allOf:
        - $ref: '#/components/schemas/Result'
