# Relationship API Contracts - POST-Only
# Feature: 024-post-only-api
# Generated: 2025-12-22

openapi: 3.0.3
info:
  title: Relationship API (POST-Only)
  version: 2.0.0
  description: Relationship management API with POST-only endpoints

paths:
  /api/v1/relationships/query:
    post:
      summary: Query relationships
      operationId: queryRelationships
      tags: [Relationships]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRelationshipsRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedRelationshipResult'

  /api/v1/relationships/resource/query:
    post:
      summary: Query relationships by resource
      operationId: queryRelationshipsByResource
      tags: [Relationships]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryResourceRelationshipsRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelationshipsResult'

  /api/v1/relationships/get:
    post:
      summary: Get single relationship
      operationId: getRelationship
      tags: [Relationships]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetRelationshipRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelationshipResult'

  /api/v1/relationships/create:
    post:
      summary: Create relationship
      operationId: createRelationship
      tags: [Relationships]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRelationshipRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelationshipResult'

  /api/v1/relationships/update:
    post:
      summary: Update relationship
      operationId: updateRelationship
      tags: [Relationships]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRelationshipRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelationshipResult'

  /api/v1/relationships/delete:
    post:
      summary: Delete relationship
      operationId: deleteRelationship
      tags: [Relationships]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteRelationshipRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoidResult'

  /api/v1/relationships/resource/cycle-detection:
    post:
      summary: Detect cycles in relationships
      operationId: detectCycles
      tags: [Relationships]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CycleDetectionRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CycleDetectionResult'

  /api/v1/relationships/resource/traverse:
    post:
      summary: Traverse relationships
      operationId: traverseRelationships
      tags: [Relationships]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TraverseRelationshipsRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraversalResult'

components:
  schemas:
    GatewayInjectableRequest:
      type: object
      properties:
        tenantId:
          type: integer
          format: int64
        traceId:
          type: string
        userId:
          type: string

    QueryRelationshipsRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          properties:
            page:
              type: integer
              minimum: 1
              default: 1
            size:
              type: integer
              minimum: 1
              maximum: 100
              default: 20
            relationType:
              type: string
            sourceId:
              type: integer
              format: int64
            targetId:
              type: integer
              format: int64

    QueryResourceRelationshipsRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [resourceId]
          properties:
            resourceId:
              type: integer
              format: int64

    GetRelationshipRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [relationshipId]
          properties:
            relationshipId:
              type: integer
              format: int64

    CreateRelationshipRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [sourceId, targetId, relationType]
          properties:
            sourceId:
              type: integer
              format: int64
            targetId:
              type: integer
              format: int64
            relationType:
              type: string
            attributes:
              type: object
              additionalProperties: true

    UpdateRelationshipRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [relationshipId]
          properties:
            relationshipId:
              type: integer
              format: int64
            attributes:
              type: object
              additionalProperties: true

    DeleteRelationshipRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [relationshipId]
          properties:
            relationshipId:
              type: integer
              format: int64

    CycleDetectionRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [resourceId]
          properties:
            resourceId:
              type: integer
              format: int64

    TraverseRelationshipsRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [resourceId]
          properties:
            resourceId:
              type: integer
              format: int64
            direction:
              type: string
              enum: [OUTGOING, INCOMING, BOTH]
              default: OUTGOING
            maxDepth:
              type: integer
              minimum: 1
              maximum: 10
              default: 3
            relationTypes:
              type: array
              items:
                type: string

    # Response schemas
    Result:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object

    RelationshipResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    PagedRelationshipResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    RelationshipsResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    VoidResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    CycleDetectionResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    TraversalResult:
      allOf:
        - $ref: '#/components/schemas/Result'
