# Resource API Contracts - POST-Only
# Feature: 024-post-only-api
# Generated: 2025-12-22

openapi: 3.0.3
info:
  title: Resource API (POST-Only)
  version: 2.0.0
  description: Resource management API with POST-only endpoints for gateway parameter injection

paths:
  /api/v1/resources/query:
    post:
      summary: Query resources list
      operationId: queryResources
      tags: [Resources]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryResourcesRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResourceResult'

  /api/v1/resources/get:
    post:
      summary: Get single resource by ID
      operationId: getResource
      tags: [Resources]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetResourceRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceResult'

  /api/v1/resources/create:
    post:
      summary: Create new resource
      operationId: createResource
      tags: [Resources]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateResourceRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceResult'

  /api/v1/resources/update:
    post:
      summary: Update existing resource
      operationId: updateResource
      tags: [Resources]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateResourceRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceResult'

  /api/v1/resources/delete:
    post:
      summary: Delete resource
      operationId: deleteResource
      tags: [Resources]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteResourceRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoidResult'

  /api/v1/resources/update-status:
    post:
      summary: Update resource status
      operationId: updateResourceStatus
      tags: [Resources]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateResourceStatusRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceResult'

  /api/v1/resources/audit-logs/query:
    post:
      summary: Query resource audit logs
      operationId: queryAuditLogs
      tags: [Resources]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryAuditLogsRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedAuditLogResult'

  /api/v1/resource-types/query:
    post:
      summary: Query resource types
      operationId: queryResourceTypes
      tags: [Resources]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryResourceTypesRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceTypesResult'

  /api/v1/resources/members/query:
    post:
      summary: Query resource members
      operationId: queryMembers
      tags: [Resource Members]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryMembersRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedMemberResult'

  /api/v1/resources/members/add:
    post:
      summary: Add members to resource
      operationId: addMembers
      tags: [Resource Members]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMembersRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoidResult'

  /api/v1/resources/members/remove:
    post:
      summary: Remove members from resource
      operationId: removeMembers
      tags: [Resource Members]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveMembersRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoidResult'

  /api/v1/resources/members-with-relations/query:
    post:
      summary: Query members with relation info
      operationId: queryMembersWithRelations
      tags: [Resource Members]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryMembersRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MembersWithRelationsResult'

  /api/v1/resources/topology/query:
    post:
      summary: Query resource topology
      operationId: queryTopology
      tags: [Resource Topology]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryTopologyRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopologyResult'

  /api/v1/resources/ancestors/query:
    post:
      summary: Query resource ancestors
      operationId: queryAncestors
      tags: [Resource Topology]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryAncestorsRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AncestorsResult'

components:
  schemas:
    # Base Request with Gateway Injectable Fields
    GatewayInjectableRequest:
      type: object
      properties:
        tenantId:
          type: integer
          format: int64
          description: Tenant ID (injected by gateway)
        traceId:
          type: string
          description: Trace ID (injected by gateway)
        userId:
          type: string
          description: User ID (injected by gateway)

    # Query Requests
    QueryResourcesRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          properties:
            page:
              type: integer
              minimum: 1
              default: 1
            size:
              type: integer
              minimum: 1
              maximum: 100
              default: 20
            resourceType:
              type: string
            name:
              type: string
            status:
              type: string

    GetResourceRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [id]
          properties:
            id:
              type: integer
              format: int64

    CreateResourceRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [resourceType, name]
          properties:
            resourceType:
              type: string
            name:
              type: string
            attributes:
              type: object
              additionalProperties: true

    UpdateResourceRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [id]
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            attributes:
              type: object
              additionalProperties: true

    DeleteResourceRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [id]
          properties:
            id:
              type: integer
              format: int64

    UpdateResourceStatusRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [id, status]
          properties:
            id:
              type: integer
              format: int64
            status:
              type: string

    QueryAuditLogsRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [resourceId]
          properties:
            resourceId:
              type: integer
              format: int64
            page:
              type: integer
              minimum: 1
              default: 1
            size:
              type: integer
              minimum: 1
              maximum: 100
              default: 20

    QueryResourceTypesRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          properties:
            page:
              type: integer
              minimum: 1
              default: 1
            size:
              type: integer
              minimum: 1
              maximum: 100
              default: 20

    # Member Requests
    QueryMembersRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [resourceId]
          properties:
            resourceId:
              type: integer
              format: int64
            page:
              type: integer
              minimum: 1
              default: 1
            size:
              type: integer
              minimum: 1
              maximum: 100
              default: 20

    AddMembersRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [resourceId, memberIds]
          properties:
            resourceId:
              type: integer
              format: int64
            memberIds:
              type: array
              items:
                type: integer
                format: int64

    RemoveMembersRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [resourceId, memberIds]
          properties:
            resourceId:
              type: integer
              format: int64
            memberIds:
              type: array
              items:
                type: integer
                format: int64

    # Topology Requests
    QueryTopologyRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [resourceId]
          properties:
            resourceId:
              type: integer
              format: int64
            depth:
              type: integer
              minimum: 1
              maximum: 10
              default: 3
            expandNested:
              type: boolean
              default: false

    QueryAncestorsRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [resourceId]
          properties:
            resourceId:
              type: integer
              format: int64

    # Response Wrappers (unchanged structure)
    Result:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object

    ResourceResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    PagedResourceResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    VoidResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    PagedAuditLogResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    ResourceTypesResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    PagedMemberResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    MembersWithRelationsResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    TopologyResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    AncestorsResult:
      allOf:
        - $ref: '#/components/schemas/Result'
