# Session API Contracts - POST-Only
# Feature: 024-post-only-api
# Generated: 2025-12-22

openapi: 3.0.3
info:
  title: Session API (POST-Only)
  version: 2.0.0
  description: Session management API with POST-only endpoints

paths:
  /api/v1/sessions/validate:
    post:
      summary: Validate session token
      operationId: validateSession
      tags: [Sessions]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateSessionRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionValidationResult'

  /api/v1/sessions/query:
    post:
      summary: Query sessions
      operationId: querySessions
      tags: [Sessions]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuerySessionsRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedSessionResult'

  /api/v1/sessions/terminate:
    post:
      summary: Terminate session
      operationId: terminateSession
      tags: [Sessions]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TerminateSessionRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoidResult'

  # SessionCompatController (legacy compatibility)
  /api/v1/session/validate:
    post:
      summary: Validate session (compat endpoint)
      operationId: validateSessionCompat
      tags: [Sessions]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateSessionRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionValidationResult'

components:
  schemas:
    GatewayInjectableRequest:
      type: object
      properties:
        tenantId:
          type: integer
          format: int64
        traceId:
          type: string
        userId:
          type: string

    ValidateSessionRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [token]
          properties:
            token:
              type: string
              description: Session token to validate (moved from header)

    QuerySessionsRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          properties:
            page:
              type: integer
              minimum: 1
              default: 1
            size:
              type: integer
              minimum: 1
              maximum: 100
              default: 20
            userId:
              type: string
            status:
              type: string
              enum: [ACTIVE, EXPIRED, TERMINATED]

    TerminateSessionRequest:
      allOf:
        - $ref: '#/components/schemas/GatewayInjectableRequest'
        - type: object
          required: [sessionId]
          properties:
            sessionId:
              type: string

    # Response schemas
    Result:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object

    SessionValidationResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    PagedSessionResult:
      allOf:
        - $ref: '#/components/schemas/Result'

    VoidResult:
      allOf:
        - $ref: '#/components/schemas/Result'
