# Relationship API Contract (保持不变)
# 本文件记录现有 API，本次重构不修改 API 契约

openapi: 3.0.3
info:
  title: Relationship API (保持不变)
  description: |
    节点关系管理 API（POST-Only）

    **重构说明**：本次重构仅修改内部实现（改用 Node2Node），API 路径和参数格式保持不变。
  version: 1.0.0

servers:
  - url: /api/service/v1

paths:
  /relationships/create:
    post:
      summary: 创建关系
      tags: [Relationships]
      description: 保持不变

  /relationships/query:
    post:
      summary: 分页查询关系
      tags: [Relationships]
      description: 保持不变

  /relationships/resource/query:
    post:
      summary: 查询资源的所有关系
      tags: [Relationships]
      description: 保持不变

  /relationships/get:
    post:
      summary: 获取单个关系
      tags: [Relationships]
      description: 保持不变

  /relationships/update:
    post:
      summary: 更新关系
      tags: [Relationships]
      description: 保持不变

  /relationships/delete:
    post:
      summary: 删除关系
      tags: [Relationships]
      description: 保持不变

  /relationships/resource/cycle-detection:
    post:
      summary: 循环依赖检测
      tags: [Relationships]
      description: 保持不变

  /relationships/resource/traverse:
    post:
      summary: 图遍历
      tags: [Relationships]
      description: 保持不变

# 注意：详细的请求/响应 schema 参见现有代码：
# - RelationshipController.java
# - CreateRelationshipRequest.java
# - UpdateRelationshipRequest.java
# - RelationshipDTO.java
# 等文件
