openapi: 3.0.0
info:
  title: AIOps 用户认证 API
  version: 1.0.0
  description: 用户名密码登录功能的 RESTful API 规范

servers:
  - url: http://localhost:8080/api/v1
    description: 本地开发环境
  - url: https://aiops.example.com/api/v1
    description: 生产环境

tags:
  - name: 认证
    description: 用户认证相关接口
  - name: 会话
    description: 会话管理相关接口
  - name: 管理员
    description: 管理员功能接口

paths:
  /auth/register:
    post:
      tags:
        - 认证
      summary: 用户注册
      description: 创建新用户账号
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: 注册成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: 请求参数无效
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: 用户名或邮箱已存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/login:
    post:
      tags:
        - 认证
      summary: 用户登录
      description: 使用用户名/邮箱和密码登录
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: 请求参数无效
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 用户名或密码错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '423':
          description: 账号已锁定
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountLockedResponse'

  /auth/logout:
    post:
      tags:
        - 认证
      summary: 用户登出
      description: 使当前会话失效
      operationId: logout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 登出成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '401':
          description: 未授权（Token 无效或过期）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /session/validate:
    get:
      tags:
        - 会话
      summary: 验证会话
      description: 验证当前 JWT Token 是否有效
      operationId: validateSession
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 会话有效
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionValidationResponse'
        '401':
          description: 会话无效或已过期
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /session/force-logout-others:
    post:
      tags:
        - 会话
      summary: 强制登出其他设备
      description: 使其他设备的会话失效，并在当前设备重新登录
      operationId: forceLogoutOthers
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForceLogoutRequest'
      responses:
        '200':
          description: 强制登出成功，返回新的 Token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: 未授权
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /admin/accounts/{accountId}/unlock:
    post:
      tags:
        - 管理员
      summary: 手动解锁账号
      description: 管理员手动解除账号锁定状态
      operationId: unlockAccount
      security:
        - bearerAuth: []
      parameters:
        - name: accountId
          in: path
          required: true
          description: 账号 ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 解锁成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: 账号未被锁定
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未授权
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 无权限（非管理员）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 账号不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 20
          pattern: '^[a-zA-Z0-9_]+$'
          description: 用户名（3-20个字符，字母数字下划线）
          example: john_doe
        email:
          type: string
          format: email
          maxLength: 100
          description: 邮箱地址
          example: john@example.com
        password:
          type: string
          minLength: 8
          maxLength: 64
          description: 密码（8-64个字符，需符合强度要求）
          example: SecureP@ss123

    RegisterResponse:
      type: object
      properties:
        code:
          type: integer
          example: 0
          description: 响应码（0表示成功）
        message:
          type: string
          example: 注册成功
        data:
          type: object
          properties:
            userId:
              type: integer
              format: int64
              example: 12345
            username:
              type: string
              example: john_doe

    LoginRequest:
      type: object
      required:
        - identifier
        - password
      properties:
        identifier:
          type: string
          description: 用户名或邮箱
          example: john_doe
        password:
          type: string
          description: 密码
          example: SecureP@ss123
        rememberMe:
          type: boolean
          default: false
          description: 是否记住我（延长会话至30天）

    LoginResponse:
      type: object
      properties:
        code:
          type: integer
          example: 0
        message:
          type: string
          example: 登录成功
        data:
          type: object
          properties:
            token:
              type: string
              description: JWT Token
              example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
            expiresAt:
              type: string
              format: date-time
              description: Token 过期时间
              example: 2025-01-23T12:30:00Z
            user:
              $ref: '#/components/schemas/UserInfo'

    UserInfo:
      type: object
      properties:
        userId:
          type: integer
          format: int64
          example: 12345
        username:
          type: string
          example: john_doe
        email:
          type: string
          example: john@example.com
        role:
          type: string
          enum: [ROLE_USER, ROLE_ADMIN]
          example: ROLE_USER

    SessionValidationResponse:
      type: object
      properties:
        code:
          type: integer
          example: 0
        message:
          type: string
          example: 会话有效
        data:
          type: object
          properties:
            valid:
              type: boolean
              example: true
            user:
              $ref: '#/components/schemas/UserInfo'
            expiresAt:
              type: string
              format: date-time
              example: 2025-01-23T12:30:00Z

    ForceLogoutRequest:
      type: object
      required:
        - password
      properties:
        password:
          type: string
          description: 当前用户密码（用于验证身份）
          example: SecureP@ss123

    AccountLockedResponse:
      type: object
      properties:
        code:
          type: integer
          example: 423
        message:
          type: string
          example: 账号已锁定，请在30分钟后重试
        data:
          type: object
          properties:
            lockedUntil:
              type: string
              format: date-time
              description: 锁定截止时间
              example: 2025-01-23T11:00:00Z
            remainingMinutes:
              type: integer
              description: 剩余锁定时间（分钟）
              example: 25

    SuccessResponse:
      type: object
      properties:
        code:
          type: integer
          example: 0
        message:
          type: string
          example: 操作成功
        data:
          type: object
          nullable: true

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: 错误码
          example: 400
        message:
          type: string
          description: 错误消息
          example: 请求参数无效
        data:
          type: object
          nullable: true
          properties:
            field:
              type: string
              description: 错误字段
              example: password
            detail:
              type: string
              description: 详细错误信息
              example: 密码长度至少为8个字符
